name: Build Java Lambda

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -f lambda/pom.xml clean package

    - name: Package Lambda ZIP
      run: |
        mkdir -p build
        zip -j build/lambda.zip lambda/target/*.jar

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-package
        path: build/lambda.zip